(function() {

  'use strict';

  angular
    .module('mockdata')
    .value('mockCountryList', [{
        "description": "Andorra",
        "value": "AD"
    }, {
        "description": "United Arab Emirates",
        "value": "AE"
    }, {
        "description": "Antigua and Barbuda",
        "value": "AG"
    }, {
        "description": "Anguilla",
        "value": "AI"
    }, {
        "description": "Albania",
        "value": "AL"
    }, {
        "description": "Armenia",
        "value": "AM"
    }, {
        "description": "Netherlands Antilles",
        "value": "AN"
    }, {
        "description": "Angola",
        "value": "AO"
    }, {
        "description": "Antarctica",
        "value": "AQ"
    }, {
        "description": "Argentina",
        "value": "AR"
    }, {
        "description": "American Samoa",
        "value": "AS"
    }, {
        "description": "Austria",
        "value": "AT"
    }, {
        "description": "Australia",
        "value": "AU"
    }, {
        "description": "Aruba",
        "value": "AW"
    }, {
        "description": "Azerbaijan",
        "value": "AZ"
    }, {
        "description": "Bosnia and Herzegovina",
        "value": "BA"
    }, {
        "description": "Barbados",
        "value": "BB"
    }, {
        "description": "Bangladesh",
        "value": "BD"
    }, {
        "description": "Belgium",
        "value": "BE"
    }, {
        "description": "Burkina Faso",
        "value": "BF"
    }, {
        "description": "Bulgaria",
        "value": "BG"
    }, {
        "description": "Bahrain",
        "value": "BH"
    }, {
        "description": "Burundi",
        "value": "BI"
    }, {
        "description": "Benin",
        "value": "BJ"
    }, {
        "description": "Saint Barthelemy",
        "value": "BL"
    }, {
        "description": "Bermuda",
        "value": "BM"
    }, {
        "description": "Brunei",
        "value": "BN"
    }, {
        "description": "Bolivia",
        "value": "BO"
    }, {
        "description": "Brazil",
        "value": "BR"
    }, {
        "description": "Bahamas",
        "value": "BS"
    }, {
        "description": "Bhutan",
        "value": "BT"
    }, {
        "description": "Botswana",
        "value": "BW"
    }, {
        "description": "Belarus",
        "value": "BY"
    }, {
        "description": "Belize",
        "value": "BZ"
    }, {
        "description": "Canada",
        "value": "CA"
    }, {
        "description": "Cocos (Keeling) Islands",
        "value": "CC"
    }, {
        "description": "Democratic Republic of the Congo",
        "value": "CD"
    }, {
        "description": "Central African Republic",
        "value": "CF"
    }, {
        "description": "Republic of the Congo",
        "value": "CG"
    }, {
        "description": "Switzerland",
        "value": "CH"
    }, {
        "description": "Ivory Coast",
        "value": "CI"
    }, {
        "description": "Cook Islands",
        "value": "CK"
    }, {
        "description": "Chile",
        "value": "CL"
    }, {
        "description": "Cameroon",
        "value": "CM"
    }, {
        "description": "China",
        "value": "CN"
    }, {
        "description": "Colombia",
        "value": "CO"
    }, {
        "description": "Costa Rica",
        "value": "CR"
    }, {
        "description": "Cuba",
        "value": "CU"
    }, {
        "description": "Cape Verde",
        "value": "CV"
    }, {
        "description": "Christmas Island",
        "value": "CX"
    }, {
        "description": "Cyprus",
        "value": "CY"
    }, {
        "description": "Czech Republic",
        "value": "CZ"
    }, {
        "description": "Germany",
        "value": "DE"
    }, {
        "description": "Djibouti",
        "value": "DJ"
    }, {
        "description": "Denmark",
        "value": "DK"
    }, {
        "description": "Dominica",
        "value": "DM"
    }, {
        "description": "Dominican Republic",
        "value": "DO"
    }, {
        "description": "Algeria",
        "value": "DZ"
    }, {
        "description": "Ecuador",
        "value": "EC"
    }, {
        "description": "Estonia",
        "value": "EE"
    }, {
        "description": "Egypt",
        "value": "EG"
    }, {
        "description": "Western Sahara",
        "value": "EH"
    }, {
        "description": "Eritrea",
        "value": "ER"
    }, {
        "description": "Spain",
        "value": "ES"
    }, {
        "description": "Ethiopia",
        "value": "ET"
    }, {
        "description": "Finland",
        "value": "FI"
    }, {
        "description": "Fiji",
        "value": "FJ"
    }, {
        "description": "Falkland Islands",
        "value": "FK"
    }, {
        "description": "Micronesia",
        "value": "FM"
    }, {
        "description": "Faroe Islands",
        "value": "FO"
    }, {
        "description": "France",
        "value": "FR"
    }, {
        "description": "Gabon",
        "value": "GA"
    }, {
        "description": "United Kingdom",
        "value": "GB"
    }, {
        "description": "Grenada",
        "value": "GD"
    }, {
        "description": "Georgia",
        "value": "GE"
    }, {
        "description": "Ghana",
        "value": "GH"
    }, {
        "description": "Gibraltar",
        "value": "GI"
    }, {
        "description": "Greenland",
        "value": "GL"
    }, {
        "description": "Gambia",
        "value": "GM"
    }, {
        "description": "Guinea",
        "value": "GN"
    }, {
        "description": "Equatorial Guinea",
        "value": "GQ"
    }, {
        "description": "Greece",
        "value": "GR"
    }, {
        "description": "Guatemala",
        "value": "GT"
    }, {
        "description": "Guam",
        "value": "GU"
    }, {
        "description": "Guinea-Bissau",
        "value": "GW"
    }, {
        "description": "Guyana",
        "value": "GY"
    }, {
        "description": "Hong Kong",
        "value": "HK"
    }, {
        "description": "Honduras",
        "value": "HN"
    }, {
        "description": "Croatia",
        "value": "HR"
    }, {
        "description": "Haiti",
        "value": "HT"
    }, {
        "description": "Hungary",
        "value": "HU"
    }, {
        "description": "Indonesia",
        "value": "ID"
    }, {
        "description": "Ireland",
        "value": "IE"
    }, {
        "description": "Israel",
        "value": "IL"
    }, {
        "description": "Isle of Man",
        "value": "IM"
    }, {
        "description": "India",
        "value": "IN"
    }, {
        "description": "British Indian Ocean Territory",
        "value": "IO"
    }, {
        "description": "Iraq",
        "value": "IQ"
    }, {
        "description": "Iran",
        "value": "IR"
    }, {
        "description": "Iceland",
        "value": "IS"
    }, {
        "description": "Italy",
        "value": "IT"
    }, {
        "description": "Jersey",
        "value": "JE"
    }, {
        "description": "Jamaica",
        "value": "JM"
    }, {
        "description": "Jordan",
        "value": "JO"
    }, {
        "description": "Japan",
        "value": "JP"
    }, {
        "description": "Kenya",
        "value": "KE"
    }, {
        "description": "Kyrgyzstan",
        "value": "KG"
    }, {
        "description": "Cambodia",
        "value": "KH"
    }, {
        "description": "Kiribati",
        "value": "KI"
    }, {
        "description": "Comoros",
        "value": "KM"
    }, {
        "description": "Saint Kitts and Nevis",
        "value": "KN"
    }, {
        "description": "North Korea",
        "value": "KP"
    }, {
        "description": "South Korea",
        "value": "KR"
    }, {
        "description": "Kuwait",
        "value": "KW"
    }, {
        "description": "Cayman Islands",
        "value": "KY"
    }, {
        "description": "Kazakhstan",
        "value": "KZ"
    }, {
        "description": "Laos",
        "value": "LA"
    }, {
        "description": "Lebanon",
        "value": "LB"
    }, {
        "description": "Saint Lucia",
        "value": "LC"
    }, {
        "description": "Liechtenstein",
        "value": "LI"
    }, {
        "description": "Sri Lanka",
        "value": "LK"
    }, {
        "description": "Liberia",
        "value": "LR"
    }, {
        "description": "Lesotho",
        "value": "LS"
    }, {
        "description": "Lithuania",
        "value": "LT"
    }, {
        "description": "Luxembourg",
        "value": "LU"
    }, {
        "description": "Latvia",
        "value": "LV"
    }, {
        "description": "Libya",
        "value": "LY"
    }, {
        "description": "Morocco",
        "value": "MA"
    }, {
        "description": "Monaco",
        "value": "MC"
    }, {
        "description": "Moldova",
        "value": "MD"
    }, {
        "description": "Montenegro",
        "value": "ME"
    }, {
        "description": "Saint Martin",
        "value": "MF"
    }, {
        "description": "Madagascar",
        "value": "MG"
    }, {
        "description": "Marshall Islands",
        "value": "MH"
    }, {
        "description": "Macedonia",
        "value": "MK"
    }, {
        "description": "Mali",
        "value": "ML"
    }, {
        "description": "Burma (Myanmar)",
        "value": "MM"
    }, {
        "description": "Mongolia",
        "value": "MN"
    }, {
        "description": "Macau",
        "value": "MO"
    }, {
        "description": "Northern Mariana Islands",
        "value": "MP"
    }, {
        "description": "Mauritania",
        "value": "MR"
    }, {
        "description": "Montserrat",
        "value": "MS"
    }, {
        "description": "Malta",
        "value": "MT"
    }, {
        "description": "Mauritius",
        "value": "MU"
    }, {
        "description": "Maldives",
        "value": "MV"
    }, {
        "description": "Malawi",
        "value": "MW"
    }, {
        "description": "Mexico",
        "value": "MX"
    }, {
        "description": "Malaysia",
        "value": "MY"
    }, {
        "description": "Mozambique",
        "value": "MZ"
    }, {
        "description": "Namibia",
        "value": "NA"
    }, {
        "description": "New Caledonia",
        "value": "NC"
    }, {
        "description": "Niger",
        "value": "NE"
    }, {
        "description": "Nigeria",
        "value": "NG"
    }, {
        "description": "Nicaragua",
        "value": "NI"
    }, {
        "description": "Netherlands",
        "value": "NL"
    }, {
        "description": "Norway",
        "value": "NO"
    }, {
        "description": "Nepal",
        "value": "NP"
    }, {
        "description": "Nauru",
        "value": "NR"
    }, {
        "description": "Niue",
        "value": "NU"
    }, {
        "description": "New Zealand",
        "value": "NZ"
    }, {
        "description": "Oman",
        "value": "OM"
    }, {
        "description": "Panama",
        "value": "PA"
    }, {
        "description": "Peru",
        "value": "PE"
    }, {
        "description": "French Polynesia",
        "value": "PF"
    }, {
        "description": "Papua New Guinea",
        "value": "PG"
    }, {
        "description": "Philippines",
        "value": "PH"
    }, {
        "description": "Pakistan",
        "value": "PK"
    }, {
        "description": "Poland",
        "value": "PL"
    }, {
        "description": "Saint Pierre and Miquelon",
        "value": "PM"
    }, {
        "description": "Pitcairn Islands",
        "value": "PN"
    }, {
        "description": "Puerto Rico",
        "value": "PR"
    }, {
        "description": "Portugal",
        "value": "PT"
    }, {
        "description": "Palau",
        "value": "PW"
    }, {
        "description": "Paraguay",
        "value": "PY"
    }, {
        "description": "Qatar",
        "value": "QA"
    }, {
        "description": "Romania",
        "value": "RO"
    }, {
        "description": "Serbia",
        "value": "RS"
    }, {
        "description": "Russia",
        "value": "RU"
    }, {
        "description": "Rwanda",
        "value": "RW"
    }, {
        "description": "Saudi Arabia",
        "value": "SA"
    }, {
        "description": "Solomon Islands",
        "value": "SB"
    }, {
        "description": "Seychelles",
        "value": "SC"
    }, {
        "description": "Sudan",
        "value": "SD"
    }, {
        "description": "Sweden",
        "value": "SE"
    }, {
        "description": "Singapore",
        "value": "SG"
    }, {
        "description": "Saint Helena",
        "value": "SH"
    }, {
        "description": "Slovenia",
        "value": "SI"
    }, {
        "description": "Svalbard",
        "value": "SJ"
    }, {
        "description": "Slovakia",
        "value": "SK"
    }, {
        "description": "Sierra Leone",
        "value": "SL"
    }, {
        "description": "San Marino",
        "value": "SM"
    }, {
        "description": "Senegal",
        "value": "SN"
    }, {
        "description": "Somalia",
        "value": "SO"
    }, {
        "description": "Suriname",
        "value": "SR"
    }, {
        "description": "Sao Tome and Principe",
        "value": "ST"
    }, {
        "description": "El Salvador",
        "value": "SV"
    }, {
        "description": "Syria",
        "value": "SY"
    }, {
        "description": "Swaziland",
        "value": "SZ"
    }, {
        "description": "Turks and Caicos Islands",
        "value": "TC"
    }, {
        "description": "Chad",
        "value": "TD"
    }, {
        "description": "Togo",
        "value": "TG"
    }, {
        "description": "Thailand",
        "value": "TH"
    }, {
        "description": "Tajikistan",
        "value": "TJ"
    }, {
        "description": "Tokelau",
        "value": "TK"
    }, {
        "description": "Timor-Leste",
        "value": "TL"
    }, {
        "description": "Turkmenistan",
        "value": "TM"
    }, {
        "description": "Tunisia",
        "value": "TN"
    }, {
        "description": "Tonga",
        "value": "TO"
    }, {
        "description": "Turkey",
        "value": "TR"
    }, {
        "description": "Trinidad and Tobago",
        "value": "TT"
    }, {
        "description": "Tuvalu",
        "value": "TV"
    }, {
        "description": "Taiwan",
        "value": "TW"
    }, {
        "description": "Tanzania",
        "value": "TZ"
    }, {
        "description": "Ukraine",
        "value": "UA"
    }, {
        "description": "Uganda",
        "value": "UG"
    }, {
        "description": "United States",
        "value": "US"
    }, {
        "description": "Uruguay",
        "value": "UY"
    }, {
        "description": "Uzbekistan",
        "value": "UZ"
    }, {
        "description": "Holy See (Vatican City)",
        "value": "VA"
    }, {
        "description": "Saint Vincent and the Grenadines",
        "value": "VC"
    }, {
        "description": "Venezuela",
        "value": "VE"
    }, {
        "description": "British Virgin Islands",
        "value": "VG"
    }, {
        "description": "US Virgin Islands",
        "value": "VI"
    }, {
        "description": "Vietnam",
        "value": "VN"
    }, {
        "description": "Vanuatu",
        "value": "VU"
    }, {
        "description": "Wallis and Futuna",
        "value": "WF"
    }, {
        "description": "Samoa",
        "value": "WS"
    }, {
        "description": "Yemen",
        "value": "YE"
    }, {
        "description": "Mayotte",
        "value": "YT"
    }, {
        "description": "South Africa",
        "value": "ZA"
    }, {
        "description": "Zambia",
        "value": "ZM"
    }, {
        "description": "Zimbabwe",
        "value": "ZW"
    }]);

})();
